### ISSUE TITLE
Can we run our own service?

### ISSUE THREAD

**Issue by Bockit** [pwalczyszyn/npm-onupdate#3]
Hi, I noticed that the server is currently out of date. I was wondering if the service is available to run ourselves? Also, is the code for the service available anywhere?

**Comment by pwalczyszyn** [comment]
Hi @Bockit sure the server code is available here: 
https://github.com/pwalczyszyn/npm-onupdate-server

**Comment by Bockit** [comment]
Oh, awesome thanks!
